### ISSUE TITLE
Way cool! Thinking of publishing?

### ISSUE THREAD

**Issue by brianegan** [localhurst/angular_redux_dev_tools#1]
Hey hey... Thanks for writing this component up! Really cool work :)

Are you thinking of publishing this to the pub website at all? Happy to link from the Redux readme if so!

**Comment by localhurst** [comment]
Version 0.2.0 up at https://pub.dartlang.org/packages/angular_redux_dev_tools

**Comment by brianegan** [comment]
Cool, I'll add it to the Redux repo :)
